---

- name: permit traffic in default zone for http service
  ansible.builtin.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: permit traffic in default zone for https service
  ansible.builtin.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

...