---

- name: Install nginx
  include: nginx-install.yml

- name: Prerequisites instalation
  include: php-install.yml

- name: Install unzip
  yum:
    name: unzip
    state: present

- name: Download and install nextcloud
  unarchive:
    src: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: /var/www/nextcloud/
    remote_src: yes
    owner: nginx
    group: nginx
    mode: 0750

- name: Selinux configuration
  include: selinux-config.yml

#- name: Configuration php.ini 


#- name: Add nginx configuration for nextcloud



...