---

- name: Add nginx stable repo
  ansible.builtin.template:
    src: nginx-repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: '0644'

- name: Install nginx stable
  yum:
    name: nginx
    state: present

- name: Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Add nginx configuration for nextcloud
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/nextcloud.conf
    owner: root
    group: root
    mode: '0644'

- name: Create ssl dir for nginx
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'  

- name: Copy crt file for ngin
  ansible.builtin.copy:
    src: files/danielyan.com.crt
    dest: /etc/nginx/ssl
    owner: root
    group: root
    mode: '0644'

- name: Copy key files for nginx
  ansible.builtin.copy:
    src: files/danielyan.com.key
    dest: /etc/nginx/ssl
    owner: root
    group: root
    mode: '0644'

...