---

- name: Add nginx stable repo
  ansible.builtin.template:
    src: nginx-repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: '0644'

- name: Install nginx stable
  yum:
    name: nginx
    state: present

- name: Remove default nginx config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default
    state: absent

...