---

- name: Change php opcache config opcache.enable
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^opcache.enable'
    line: opcache.enable=1

- name: Change php opcache config opcache.memory_consumption
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^opcache.memory_consumption'
    line: opcache.memory_consumption=128

- name: Change php opcache config opcache.interned_strings_buffer
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^opcache.interned_strings_buffer'
    line: opcache.interned_strings_buffer=8

- name: Change php opcache config max_accelerated_files
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^opcache.max_accelerated_files'
    line: opcache.max_accelerated_files=10000

- name: Change php opcache config opcache.revalidate_freq
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^\;opcache.revalidate_freq'
    line: opcache.revalidate_freq=1

- name: Change php opcache config opcache.save_comments
  ansible.builtin.lineinfile:
    path: /etc/php.d/10-opcache.ini
    regexp: '^\;opcache.save_comments'
    line: opcache.save_comments=1

...