---

- name: Install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install the remi repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Remove repository remi-php54
  yum_repository:
    name: remi-php54
    state: absent

- name: Install php
  yum:
    name: "{{ php_install }}"
    state: present
    enablerepo: "remi-php73"
  #with_items:
  #    - "{{ php_install }}"

...