---

- name: restart nginx
  ansible.builtin.systemd:
     name: nginx
     state: restarted

- name: restart php-fpm
  ansible.builtin.systemd:
     name: php-fpm
     state: restarted

- name: restart redis
  ansible.builtin.systemd:
     name: redis
     state: restarted

...